import "Filme.dart";


final List<Filme> filmes = [
  Filme(
    nome: "Cidade de Deus",
    sinopse:
        "Dadinho (Douglas Silva) e Buscapé são grandes amigos, que cresceram juntos imersos em um universo de muita violência. Na Cidade de Deus, favela carioca conhecida por ser um dos locais mais violentos do Rio de Janeiro, os caminhos das duas crianças divergem, quando um se esforça para se tornar um fotógrafo e o outro o chefe do tráfico. Buscapé (Alexandre Rodrigues) é um jovem pobre, negro e muito sensível, que vive amedrontado com a possibilidade de se tornar um bandido, e acaba sendo salvo de seu destino por causa de seu talento como fotógrafo, o qual permite que siga carreira na profissão. É através de seu olhar atrás da câmera que Buscapé analisa o dia-a-dia da favela onde vive, enquanto Dadinho, agora Zé Pequeno (Leandro Firmino), se torna o temido chefe do tráfico da região, continuando com o legado de violência que remonta a décadas anteriores - e parece ser infinita. Considerado um dos melhores filmes da história do cinema brasileiro.",
    direcao: "Fernando Meirelles, Kátia Lund",
    empresa: "O2 Filmes, Globo Filmes",
    genero: "Drama, Crime",
    dataLancamento: "2002",
    elenco: "Alexandre Rodrigues, Leandro Firmino, Seu Jorge",
    trailer:"https://www.youtube.com/watch?v=fZJUKixyeXM",
    galeria: [
      "Img/cidade/Deuscapa.png",
      "Img/cidade/imagem1.jpg",
      "Img/cidade/imagem2.webp",
      "Img/cidade/imagem3.jpg",
      "Img/cidade/imagem4.jpg",
    ],
    avaliacao: 4.9,
    imagemPrincipal: "Img/cidade/Deuscapa.png",
  ),
  Filme(
    nome: "Mãos Talentosas",
    sinopse:
        "Ben Carson (Cuba Gooding Jr.), menino pobre de Detroit, sempre levou uma vida desmotivada, já que tirava notas baixas e não tinha perspectivas de um grande futuro.\n O que ele e os que estavam ao redor não esperavam era que ele se tornaria um neurocirurgião de fama mundial.",
    direcao: "Thomas Carter",
    empresa: "Sony Pictures Television",
    genero: "Biografia, Drama",
    dataLancamento: "2009",
    elenco: "Cuba Gooding Jr., Kimberly Elise",
    trailer:"https://www.youtube.com/watch?v=ayAaXVx_YVo",
    galeria: [
      "Img/talentosas/capa.jpg",
      "Img/talentosas/imagem1.webp",
      "Img/talentosas/imagem2.jpg",
      "Img/talentosas/imagem3.jpg",
      "Img/talentosas/imagem4.jpg",
    ],
    avaliacao: 4.7,
    imagemPrincipal: "Img/talentosas/capa.jpg",
  ),
  Filme(
    nome: "O Senhor dos Anéis: A Sociedade do Anel",
    sinopse:
        "Numa terra fantástica e única, chamada Terra-Média, um hobbit (seres de estatura entre 80 cm e 1,20 m, com pés peludos e bochechas um pouco avermelhadas) recebe de presente de seu tio o Um Anel, um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso o hobbit Frodo (Elijah Woods) terá um caminho árduo pela frente, onde encontrará perigo, medo e personagens bizarros. Ao seu lado para o cumprimento desta jornada aos poucos ele poderá contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando 9 pessoas que formarão a Sociedade do Anel.",
    direcao: "Peter Jackson",
    empresa: "New Line Cinema",
    genero: "Fantasia, Aventura",
    dataLancamento: "2001",
    elenco: "Elijah Wood, Ian McKellen, Viggo Mortensen",
    trailer:"https://www.youtube.com/watch?v=0i86oM1nHjM",
    galeria: [
      "Img/sociAnel/capa.jpg",
      "Img/sociAnel/imagem1.jpg",
      "Img/sociAnel/imagem2.webp",
      "Img/sociAnel/imagem3.jpg",
      "Img/sociAnel/imagem1.jpg",
    ],
    avaliacao: 5.0,
    imagemPrincipal: "Img/sociAnel/capa.jpg",
  ),
  Filme(
    nome: "O Senhor dos Anéis: As Duas Torres",
    sinopse:
        "Após a captura de Merry (Dominic Monaghan) e Pippy (Billy Boyd) pelos orcs, a Sociedade do Anel é dissolvida. Enquanto que Frodo (Elijah Wood) e Sam (Sean Astin) seguem sua jornada rumo à Montanha da Perdição para destruir o Um Anel, Aragorn (Viggo Mortensen), Legolas (Orlando Bloom) e Gimli (John Rhys-Davies) partem para resgatar os hobbits sequestrados.",
    direcao: "Peter Jackson",
    empresa: "New Line Cinema",
    genero: "Fantasia, Aventura",
    dataLancamento: "2002",
    elenco: "Elijah Wood, Ian McKellen, Orlando Bloom",
    trailer:"https://www.youtube.com/watch?v=Al5iC4CnhYc",
    galeria: [
      "Img/duastorre/capa.jpg",
      "Img/duastorre/imagem1.jpg",
      "Img/duastorre/imagem2.jpg",
      "Img/duastorre/imagem3.jpg",
      "Img/duastorre/imagem4.jpg",
      "Img/duastorre/imagem5.jpg",
    ],
    avaliacao: 4.9,
    imagemPrincipal: "Img/duastorre/capa.jpg",
  ),
  Filme(
    nome: "O Senhor dos Anéis: O Retorno do Rei",
    sinopse:
        "Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf (Ian McKellen) e Pippin (Billy Boyd) partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden (Bernard Hill) em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso Frodo (Elijah Wood), Sam (Sean Astin) e Gollum (Andy Serkins) seguem sua viagem rumo à Montanha da Perdição, para destruir o Um Anel.",
    direcao: "Peter Jackson",
    empresa: "New Line Cinema",
    genero: "Fantasia, Aventura",
    dataLancamento: "2003",
    elenco: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    trailer:"https://www.youtube.com/watch?v=LiKeQrChkTY",
    galeria: [
      "Img/returnrei/capa1.jpg",
      "Img/returnrei/imagem1.jpg",
      "Img/returnrei/imagem2.webp",
      "Img/returnrei/imagem3.webp",
      "Img/returnrei/imagem4.webp",
      "Img/returnrei/imagem5.jpg",
    ],
    avaliacao: 5.0,
    imagemPrincipal: "Img/returnrei/capa1.jpg",
  ),
  Filme(
    nome: "Indiana Jones e os Caçadores da Arca Perdida",
    sinopse:
        "Em 1936, o arqueólogo e aventureiro Indiana Jones é contratado pelo governo americano para encontrar a Arca da Aliança, um artefato bíblico que conteria os Dez Mandamentos. A missão se torna mais perigosa ao saber que os nazistas também estão atrás da relíquia sagrada, que daria a quem a possuir um poder inimaginável. Com a ajuda de Marion e Sallah, Indy viaja por diferentes países em busca da Arca, enfrentando armadilhas mortais, rivais perigosos e dilemas morais.",
    direcao: "Steven Spielberg",
    empresa: "Paramount Pictures",
    genero: "Aventura, Ação",
    dataLancamento: "1981",
    elenco: "Harrison Ford, Karen Allen, Paul Freeman",
    trailer: "https://www.youtube.com/watch?v=XkkzKHCx154",
    galeria: [
      "Img/IJarca/capa.jpg",
      "Img/IJarca/imagem1.jpeg",
      "Img/IJarca/imagem2.jpeg",
      "Img/IJarca/imagem3.jpg",
      "Img/IJarca/imagem4.webp",
    ],
    avaliacao: 4.8,
    imagemPrincipal: "Img/IJarca/capa.jpg",
  ),
  Filme(
    nome: "Indiana Jones: O Templo da Perdição",
    sinopse:
        "Em 1935, o professor, arqueólogo e aventureiro Indiana Jones (Harrison Ford) tem uma nova missão: resgatar as pedras roubadas por um feiticeiro e libertar crianças escravizadas. Para tanto, enfrenta os poderes mágicos e o fanatismo de um culto que sacrifica seres humanos.",
    direcao: "Steven Spielberg",
    empresa: "Paramount Pictures",
    genero: "Ação, Aventura",
    dataLancamento: "1984",
    elenco: "Harrison Ford, Kate Capshaw",
    trailer: "https://www.youtube.com/watch?v=WBdyLyijZhU",
    galeria: [
      "Img/IJtemplo/capa.webp",
      "Img/IJtemplo/imagem1.jpeg",
      "Img/IJtemplo/imagem2.jpeg",
      "Img/IJtemplo/imagem3.jpg",
      "Img/IJtemplo/imagem4.jpg",
    ],
    avaliacao: 4.4,
    imagemPrincipal: "Img/IJtemplo/capa.webp",
  ),
  Filme(
    nome: "Indiana Jones: A Última Cruzada",
    sinopse:
        "O arqueólogo Indiana Jones (Harrisson Ford) tem acesso à um misterioso envelope que contém informações sobre a localização do lendário Santo Graal, o cálice que Jesus Cristo teria utilizado na Última Ceia. Quando seu pai, o professor Henry Jones (Sean Connery), é sequestrado pelos nazistas, o aventureiro irá embarcar numa missão perigosa para salvá-lo e impedir que a relíquia sagrada caia em mãos erradas.",
    direcao: "Steven Spielberg",
    empresa: "Paramount Pictures",
    genero: "Ação, Aventura",
    dataLancamento: "1989",
    elenco: "Harrison Ford, Sean Connery",
    trailer: "https://www.youtube.com/watch?v=sagmdpkWUqc",
    galeria: [
      "Img/IJcruzada/capa.webp",
      "Img/IJcruzada/imagem1.jpeg",
      "Img/IJcruzada/imagem2.jpg",
      "Img/IJcruzada/imagem3.jpg",
      "Img/IJcruzada/imagem4.jpg",
    ],
    avaliacao: 4.7,
    imagemPrincipal: "Img/IJcruzada/capa.webp",
  ),
  Filme(
    nome: "Indiana Jones: O Reino da Caveira de Cristal",
    sinopse:
        "Indiana Jones (Harrison Ford) e seu ajudante Mac (Ray Winstone) escapam por pouco de um encontro com agentes soviéticos, em um campo de pouso remoto. Agora Indiana está de volta à sua casa na Universidade Marshall, mas seu amigo e reitor da escola, Dean Stanforth (Jim Broadbent), explica que suas ações recentes o tornaram alvo de suspeita e que o governo está pressionando para que o demita. Ao deixar a cidade Indiana conhece o rebelde jovem Mutt Williams (Shia LaBeouf), que tem uma proposta: caso o ajude em uma missão Indiana pode deparar-se com a caveira de cristal de Akator. Agentes soviéticos também estão em busca do artefato, entre eles a fria e bela Irina Spalko (Cate Blanchett), cujo esquadrão de elite está cruzando o globo atrás da Caveira de Cristal.",
    direcao: "Steven Spielberg",
    empresa: "Paramount Pictures",
    genero: "Ação, Aventura, Ficção Científica",
    dataLancamento: "2008",
    elenco: "Harrison Ford, Shia LaBeouf, Cate Blanchett",
    trailer: "https://www.youtube.com/watch?v=WAdJf4wTC5Y",
    galeria: [
      "Img/IJcaveira/capa.jpg",
      "Img/IJcaveira/imagem1.jpg",
      "Img/IJcaveira/imagem2.webp",
      "Img/IJcaveira/imagem3.jpeg",
    ],
    avaliacao: 4.0,
    imagemPrincipal: "Img/IJcaveira/capa.jpg",
  ),
  Filme(
    nome: "Indiana Jones: A Relíquia do Destino",
    sinopse:
        "Em Indiana Jones e a Relíquia do Destino, Indiana Jones (Harrisson Ford), famoso arqueólogo, professor e aventureiro, embarca em mais uma missão inesperada. Neste retorno do herói lendário, Indiana Jones, na quinta parcela da icônica série de filmes, encontra-se em uma nova era, aproximando-se da aposentadoria. Ele luta para se encaixar em um mundo que parece tê-lo superado. Mas quando as garras de um mal muito familiar retornam na forma de um antigo rival, Indiana Jones deve colocar seu chapéu e pegar seu chicote mais uma vez para garantir que um antigo e poderoso artefato não caia nas mãos erradas. Mas, desta vez, ele tem o sangue de uma nova geração para o ajudar nas suas descobertas e na sua luta contra o vilão Jürgen Voller (Mads Mikkelsen). Acompanhado de sua afilhada, Helena Shaw (Phoebe Waller-Bridge), o arqueólogo corre contra o tempo para recuperar o item que pode mudar o curso da história.",
    direcao: "James Mangold",
    empresa: "Walt Disney Studios",
    genero: "Ação, Aventura",
    dataLancamento: "2023",
    elenco: "Harrison Ford, Phoebe Waller-Bridge",
    trailer: "https://www.youtube.com/watch?v=eQfMbSe7F2g",
    galeria: [
      "Img/IJdestino/capa.webp",
      "Img/IJdestino/imagem1.jpeg",
      "Img/IJdestino/imagem2.jpeg",
      "Img/IJdestino/imagem3.webp",
      "Img/IJdestino/imagem4.jpeg",
    ],
    avaliacao: 4.2,
    imagemPrincipal: "Img/IJdestino/capa.webp",
  ),
];
